websershop/webershop/accounts/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

websershop/webershop/communications/urls.py
from django.urls import path
from .views import *

app_name = "communications"

urlpatterns = [
    path('', all_messages, name="all-messages"),
    path('<slug:friend>', messages_with_one_friend, name="messages-with-one-friend"),
]

websershop/webershop/core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path('', home, name="home"),
]

websershop/webershop/notifications/urls.py
from django.urls import path
from .views import *

app_name = "notifications"

urlpatterns = [
    path('mark-like-comment-notifications-as-read', mark_like_comment_notifications_as_read, name="mark-like-comment-notifications-as-read"),
]

websershop/webershop/userprofile/urls.py
from django.urls import path
from .views import *

app_name = "profile"

urlpatterns = [
    path('edit-profile', ProfileEditView.as_view(), name="edit-profile"),
    path('<slug:username>', TimelineView.as_view(), name="user-timeline"),
]

websershop/webershop/webershop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('notifications.urls')),
    path('', include('core.urls')),
    path('', include('newsfeed.urls')),
    path('', include('friends.urls')),
    path('timeline/', include('userprofile.urls')),
    path('messages/', include('communications.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websershop/webershop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <title>Gatherly Social Network Toolkit</title>

    {% include 'includes/stylesheets.html' %}
    {% csrf_token %}

</head>
<body>
<div class="theme-layout">

    <div class="topbar stick">
        <div class="logo">
            <a title="" href="/"><img src="{% static 'images/logo.png' %}" alt="" style="height: 70px; width: 90px"></a>
        </div>

        <div class="top-area">
            <div class="top-search">
                <form method="post" class="">
                    <input type="text" placeholder="Search Friend">
                    <button data-ripple><i class="ti-search"></i></button>
                </form>
            </div>
            <ul class="setting-area">
                <li><a href="{% url 'core:home' %}" title="Home" data-ripple=""><i class="ti-home"></i></a></li>
                <li><a href="{% url 'communications:all-messages' %}" class="link">Messenger</a></li>
                <li>
                    <a href="#" title="Notification" data-ripple="">
                        <i class="ti-user"></i><span id="total-friend-notifications"></span>
                    </a>
                    <div class="dropdowns">
                        <ul class="drops-menu" id="friend-menu">
                        </ul>
                        <a href="#" title="" class="more-mesg">view more</a>
                    </div>
                </li>
                <li>
                    <a href="#" title="Messages" data-ripple=""><i class="ti-comment"></i><span id="total-like-comment-notifications">0</span></a>
                    <div class="dropdowns">
                        <ul class="drops-menu" id="like-comment-menu">
                        </ul>
                        <a href="#" title="" class="more-mesg">view more</a>
                        <a href="#" title="" class="more-mesg" data-url="{% url 'notifications:mark-like-comment-notifications-as-read' %}" id="mark-like-comment-notifications-as-read">mark all as read</a>
                    </div>
                </li>
            </ul>
            <div class="user-img">
                <img src="{{ request.user.profile.profile_image.url }}" alt="" style="height: 40px; width: 40px;">
                <span class="status f-online"></span>
                <div class="user-setting">
                    <a href="#" title=""><span class="status f-online"></span>online</a>
                    <a href="#" title=""><span class="status f-away"></span>away</a>
                    <a href="#" title=""><span class="status f-off"></span>offline</a>
                    <a href="#" title=""><i class="ti-user"></i> view profile</a>
                    <a href="{% url 'profile:edit-profile' %}" title=""><i class="ti-pencil-alt"></i>edit profile</a>
                    <a href="#" title=""><i class="ti-target"></i>activity log</a>
                    <a href="#" title=""><i class="ti-settings"></i>account setting</a>
                    <a href="{% url 'accounts:logout' %}" title=""><i class="ti-power-off"></i>log out</a>
                </div>
            </div>
            <span class="ti-menu main-menu" data-ripple=""></span>
        </div>
    </div><!-- topbar -->

    {% block content %}{% endblock %}

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-4">
                    <div class="widget">
                        <div class="widget-title"><h4>follow</h4></div>
                        <ul class="list-style">
                            <li><i class="fa fa-facebook-square"></i> <a href="https://web.facebook.com/shopcircut/" title="">facebook</a></li>
                            <li><i class="fa fa-twitter-square"></i><a href="https://twitter.com/login?lang=en" title="">twitter</a></li>
                            <li><i class="fa fa-instagram"></i><a href="https://www.instagram.com/?hl=en" title="">instagram</a></li>
                            <li><i class="fa fa-google-plus-square"></i> <a href="https://plus.google.com/discover" title="">Google+</a></li>
                            <li><i class="fa fa-pinterest-square"></i> <a href="https://www.pinterest.com/" title="">Pintrest</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-4">
                    <div class="widget">
                        <div class="widget-title"><h4>useful links</h4></div>
                        <ul class="list-style">
                            <li><a href="#" title="">leasing</a></li>
                            <li><a href="#" title="">submit route</a></li>
                            <li><a href="#" title="">how does it work?</a></li>
                            <li><a href="#" title="">agent listings</a></li>
                            <li><a href="#" title="">view All</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer><!-- footer -->
    <div class="bottombar">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <span class="copyright">©. All rights reserved.</span>
                    <i><img src="images/credit-cards.png" alt=""></i>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'includes/scripts.html' %}
{% block scripts %}{% endblock %}

</body>
</html>